[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mon-package"
version = "0.1.0"
description = "Un package Python simple et propre"
authors = [
  { name="Root@123", email="traoreera@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
        "starlette",
        "uvicorn[standard]",
        "pydantic",
        "pydantic-settings",
        "watchdog",
        "python-multipart",
        "python-jose[cryptography]",
        "passlib[bcrypt]",
        "pytest",
        "pytest-asyncio",
        "httpx",
        "mysql-connector-python",
        "sqlalchemy"
]

[project.urls]
Homepage = "https://github.com/traoreera/microframe"
Issues = "https://github.com/traoreera/microframe/issues"
